name             'network_interfaces_v2'
maintainer       'Dang H. Nguyen'
maintainer_email 'haidangwa@gmail.com'
license          'Apache-2.0'
description      'Providers for configuring network on Ubuntu, RHEL, and Windows'
source_url       'https://github.com/haidangwa/network_interfaces_v2-cookbook'
issues_url       'https://github.com/haidangwa/network_interfaces_v2-cookbook/issues'
version          '2.12.0'
chef_version     '> 15.0'

supports 'ubuntu', '>= 14.04'
supports 'windows'
supports 'redhat', '>= 6.0'
supports 'centos', '>= 6.0'

depends 'powershell', '~> 6.1.3'
